version: '3.1'

services:
  db:
    image: postgres
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: cd
      POSTGRES_PASSWORD: pw
      POSTGRES_DB:
    volumes:
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql